config/routes.rb
Bett0r::Application.routes.draw do
  namespace "admin" do
    resources :teamnames
    resources :bettypes
    resources :bookmakers do
      resources :bookie_games
      resources :teamnames
      resources :bettypes
    end
    match "teamnames/update_all" => "teamnames#update_all"
    match "bettypes/update_all" => "bettypes#update_all"
  end

  get "admin/index"
  get "admin/teamnames/index"

  get "analyzer/index"

  match "analyzer/:bookie_id" => "analyzer#index"

  resources :games

  root :to => "games#index"

end

app/models/bookmaker.rb
class Bookmaker < ActiveRecord::Base
  has_many :bookie_games do
    def find_or_create_by_home_name_and_away_name(hname, aname)
      BookieGame.find_or_create_by_bookmaker_id_and_home_name_and_away_name(proxy_owner.id, hname, aname)
    end
  end
  has_many :teamnames do
    def unmapped
      find(:all, :conditions => { :mainname_id => nil, :main => false})
    end
  end
  has_many :bettypes do
    def unmapped
      find(:all, :conditions => { :maintype_id => nil, :main => false})
    end
  end

  # validations
  validates_presence_of :name
  validates_uniqueness_of :name

  def to_s
    self.name.to_s
  end
end

app/controllers/admin/bookmakers_controller.rb
class Admin::BookmakersController < ApplicationController
  def new
    @bookie = Bookmaker.new
  end

  def create
    @bookie = Bookmaker.new(params[:bookmaker])

    if @bookie.save
      flash[:notice] = 'Bookmaker succesfully created!'
      redirect_to :controller => "/admin", :action => "index"
    else
      render :action => "new"
    end
  end

  def show
    @bookie = Bookmaker.find(params[:id])
  end

  def destroy
    @bookie = Bookmaker.find(params[:id])

    flash[:notice] = "\'#{@bookie.name}\' has been deleted!"
    @bookie.destroy
    
    redirect_to :controller => "/admin", :action => "index"
  end

  def edit
    @bookie = Bookmaker.find(params[:id])
  end

  def update
    @bookie = Bookmaker.find(params[:id])

    if @bookie.update_attributes(params[:bookmaker])
      flash[:notice] = "#{params[:post]} \'#{@bookie.name}\' was successfully updated!"
      redirect_to :controller => '/admin', :action => 'index'
    else
      render :action => "edit"
    end
  end
end

app/helpers/admin/bookmakers_helper.rb
module Admin::BookmakersHelper
end

app/views/admin/bookmakers/_form.html.erb
<%= form_for [:admin, @bookie] do |f| %>
  <% if @bookie.errors.any? %>
  <% end %>

  <div>
    <%= f.label :name %>:
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/bookmakers/edit.html.erb
<h1>Editing</h1>

<%= render 'form' %>

<%= link_to 'Back', :controller => '/admin', :action => 'index' %>

app/views/admin/bookmakers/new.html.erb
<h1>New Bookmaker</h1>

<%= render 'form' %>

app/views/admin/bookmakers/show.html.erb
<h1><%= @bookie.name %></h1>

<table>
  <tr>
    <td>Teamnames: <%= @bookie.teamnames.count %></td>
    <td>Unmapped: <%= @bookie.teamnames.unmapped.count %></td>
    <td><%= link_to 'Show', admin_bookmaker_teamnames_path(@bookie) %></td>
  </tr>
  <tr>
    <td>Bettypes: <%= @bookie.bettypes.count %></td>
    <td>Unmapped: <%= @bookie.bettypes.unmapped.count %></td>
    <td><%= link_to 'Show', admin_bookmaker_bettypes_path(@bookie) %></td>
  </tr>
  <tr>
    <td>BookieGames: <%= @bookie.bookie_games.count %></td>
    <td><%= link_to 'Show', admin_bookmaker_bookie_games_path(@bookie) %></td>
  </tr>
</table>

<p><%= link_to 'Back', :controller => '/admin', :action => 'index' %></p>