config/routes.rb
Bett0r::Application.routes.draw do
  namespace "admin" do
    resources :teamnames
    resources :bettypes
    resources :bookmakers do
      resources :bookie_games
      resources :teamnames
      resources :bettypes
    end
    match "teamnames/update_all" => "teamnames#update_all"
    match "bettypes/update_all" => "bettypes#update_all"
  end

  get "admin/index"
  get "admin/teamnames/index"

  get "analyzer/index"

  match "analyzer/:bookie_id" => "analyzer#index"

  resources :games

  root :to => "games#index"

end

app/controllers/analyzer_controller.rb
class AnalyzerController < ApplicationController
  def index
    if params[:bookie_id].nil? then
      @bets = Game.best_bets
    else
      @bets = Game.best_bets_by_bookie(Bookmaker.find(params[:bookie_id]))
    end
    @bets.sort_by! { |b| b[:per] }.reverse!
    @bets.delete_if { |b| b[:per] < 97.5 }
    Time.zone = "CET"
  end
end

app/helpers/analyzer_helper.rb
module AnalyzerHelper
end

app/views/analyzer/index.html.erb
<h2><%= @bets.count %> Bets over 98.5%</h2>

<table>
<% @bets.each do |bet| %>
  <tr>
    <td><%= bet[:game].starttime.strftime("%A, %d.%m. %H:%M") %></td>
    <td><%= link_to bet[:game], game_path(bet[:game].id) %></td>
    <td colspan="4"></td>
  </tr>
  <tr>
    <td></td>
    <td><%= bet[:bettype] %></td>
    <td><%= bet[:odd1].bookie_game.bookmaker %></td>
    <td><%= bet[:oddX].bookie_game.bookmaker unless bet[:oddX].oddX.nil? %></td>
    <td><%= bet[:odd2].bookie_game.bookmaker %></td>
    <td></td>
  </tr>
  <tr>
    <td colspan="2"></td>
    <td><%= bet[:odd1].odd1 %></td>
    <td><%= bet[:oddX].oddX %></td>
    <td><%= bet[:odd2].odd2 %></td>
    <td><%= bet[:per].round(2) %></td>
  </tr
</tr>
<% end %>
</table>